config/routes.rb
Rails.application.routes.draw do

  get 'oauths/oauth'

  get 'oauths/callback'

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :categories
    resources :goods
    resources :articles
    resources :orders do
      patch 'change_status', on: :member
    end
  end

  get '/cart', to: 'carts#show', as: 'cart'
  delete '/cart', to: 'carts#destroy', as: 'delete_cart'
  resources :cart_items, only: :destroy do
    patch 'increase', on: :member
    patch 'decrease', on: :member
  end

  resources :orders, only: [:new, :create, :show]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'profile', to: 'users#show', as: :profile
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  get 'article/:id', to: 'articles#show', as: :article

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider

  resources :users, only: [:create, :update]
  resources :sessions, only: [:create]

  get 'search', to: 'search#find', as: :search

  resources :categories, only: [:index, :show], path: 'catalog' do
    resources :goods, only: [:show], path: '' do
      post 'add_to_cart', on: :member
    end
  end

  root 'categories#index'

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  belongs_to :user

  def add_good(good)
    existed_cart_item = cart_items.find_by(good_id: good.id)
    if existed_cart_item
      existed_cart_item.quantity += 1
      existed_cart_item.save!
    else
      cart_items.create(good_id: good.id)
    end
  end

  def total_price
    cart_items.map(&:total_price).sum
  end

  def empty?
    cart_items.empty?
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  authorize_resource

  def show
    respond_with(@current_cart)
  end

  def destroy
    session[:cart_id] = nil
    @current_cart.destroy
    redirect_to cart_path
  end

end

app/views/carts/_cart.html.slim
-unless @current_cart.cart_items.empty?
  = "#{@current_cart.cart_items.includes(:good).count} #{'item'.pluralize(@current_cart.cart_items.count)}"
  br
  = "#{number_to_currency @current_cart.total_price}"
  br
  = link_to t(:show_cart), cart_path

app/views/carts/show.html.slim
-unless @current_cart.empty?
  .current_cart.col-md-12
    table.table.table-hover
      thead
        td Item name
        td Quantity
        td Price
        td Actions
      tbody
        -@current_cart.cart_items.includes(:good).each do |item|
          =content_tag(:tr, class: "item-#{item.id}")
            =render 'cart_items/cart_item_in_cart', item: item
  =link_to t(:delete_all_from_cart), delete_cart_path, method: :delete, id: 'clean-cart', class: "btn btn-danger"
  br
  =link_to t('checkout'), new_order_path, class: "btn btn-success", disabled: @current_cart.empty?