config/routes.rb
Rails.application.routes.draw do

  get 'oauths/oauth'

  get 'oauths/callback'

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :categories
    resources :goods
    resources :articles
    resources :orders do
      patch 'change_status', on: :member
    end
  end

  get '/cart', to: 'carts#show', as: 'cart'
  delete '/cart', to: 'carts#destroy', as: 'delete_cart'
  resources :cart_items, only: :destroy do
    patch 'increase', on: :member
    patch 'decrease', on: :member
  end

  resources :orders, only: [:new, :create, :show]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'profile', to: 'users#show', as: :profile
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  get 'article/:id', to: 'articles#show', as: :article

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider

  resources :users, only: [:create, :update]
  resources :sessions, only: [:create]

  get 'search', to: 'search#find', as: :search

  resources :categories, only: [:index, :show], path: 'catalog' do
    resources :goods, only: [:show], path: '' do
      post 'add_to_cart', on: :member
    end
  end

  root 'categories#index'

end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id         :integer          not null, primary key
#  cart_id    :integer
#  good_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quantity   :integer          default("1")
#  order_id   :integer
#

class CartItem < ActiveRecord::Base
  belongs_to :good
  belongs_to :cart
  belongs_to :order

  def total_price
    good.price * quantity
  end

  def change_quantity(increment)
    update(quantity: (quantity + increment)) if (quantity + increment) > 0
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  # before_action :set_cart_item
  respond_to :js
  load_and_authorize_resource
  def destroy
    @cart_item.destroy
    redirect_to '/cart'
  end

  def increase
    @cart_item.change_quantity(1)
    render 'change'
  end

  def decrease
    @cart_item.change_quantity(-1)
    render 'change'
  end

  private

  # def set_cart_item
  #   @item = CartItem.find(params[:id])
  # end

end

app/views/cart_items/_cart_item_in_cart.html.slim
td = item.good.name
td
  table.quantity
    tr
      td.quantity_value
        = item.quantity
      td
        =link_to  increase_cart_item_path(item), method: :patch, id: "increase-item-#{item.id}", remote: true
          i.glyphicon.glyphicon-arrow-up
      td
        =link_to  decrease_cart_item_path(item), method: :patch, id: "decrease-item-#{item.id}", remote: true
          i.glyphicon.glyphicon-arrow-down
td = number_to_currency item.total_price
td 
  = link_to cart_item_path(item), method: :delete, id: "remove-item-#{item.id}"
    i.glyphicon.glyphicon-remove

app/views/cart_items/change.js.erb
$('tr.item-<%= @cart_item.id %>').html('<%= j render 'cart_items/cart_item_in_cart', item: @cart_item %>')