config/routes.rb
Rails.application.routes.draw do

  get 'oauths/oauth'

  get 'oauths/callback'

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :categories
    resources :goods
    resources :articles
    resources :orders do
      patch 'change_status', on: :member
    end
  end

  get '/cart', to: 'carts#show', as: 'cart'
  delete '/cart', to: 'carts#destroy', as: 'delete_cart'
  resources :cart_items, only: :destroy do
    patch 'increase', on: :member
    patch 'decrease', on: :member
  end

  resources :orders, only: [:new, :create, :show]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'profile', to: 'users#show', as: :profile
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  get 'article/:id', to: 'articles#show', as: :article

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider

  resources :users, only: [:create, :update]
  resources :sessions, only: [:create]

  get 'search', to: 'search#find', as: :search

  resources :categories, only: [:index, :show], path: 'catalog' do
    resources :goods, only: [:show], path: '' do
      post 'add_to_cart', on: :member
    end
  end

  root 'categories#index'

end

app/models/good.rb
# == Schema Information
#
# Table name: goods
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  description :text
#  price       :decimal(5, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  sale        :boolean          default("false")
#

class Good < ActiveRecord::Base

  extend FriendlyId

  friendly_id :name, use: [:slugged, :finders]

  has_many :cart_items, dependent: :restrict_with_error
  has_many :photos, dependent: :destroy
  belongs_to :category
  validates :name, :price, :category_id, presence: true
  accepts_nested_attributes_for :photos, allow_destroy: true

  scope :sale, -> { where(sale: true) }

  def change_sale
    self.update!(sale: !sale)
  end

  def self.top_selled(limit)
    query = CartItem.select("good_id").group("good_id").order("sum(quantity) DESC").limit(limit).map(&:good_id)
    find(query)
  end

end

app/controllers/admin/goods_controller.rb
class Admin::GoodsController < Admin::AdminController
  load_and_authorize_resource

  def show
    respond_with @good
  end

  def new
    @categories = Category.all
    respond_with @good
  end

  def create
    respond_with(@good = Good.create(good_params), location: admin_path)
  end

  def edit
    @categories = Category.all
    respond_with @good
  end

  def update
    @good.update(good_params)
    respond_with(@good, location: admin_category_path(@good.category))
  end

  private
  def good_params
    params.require(:good).permit(:name, :description, :price, :category_id, :sale, photos_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController

  add_breadcrumb I18n::t(:categories), :categories_path
  respond_to :js
  load_and_authorize_resource
  def index
    respond_with @goods = Good.all
  end

  def show
    add_breadcrumb @good.category.title, category_path(@good.category)
    add_breadcrumb @good.name, category_good_path(@good.category, @good)
    respond_with @good
  end

  def add_to_cart
    @current_cart.add_good(@good)
  end

end

app/helpers/goods_helper.rb
module GoodsHelper

  def good_image(good)
    if good.photos.any? 
      image_tag good.photos.first.file.thumb.url, alt: good.name
    else
      image_tag 'photo-not-available.png'
    end
  end

  def good_image_small(good)
    if good.photos.first
      image_tag good.photos.first.file.small_thumb.url alt: good.name
    else
      "w/o photo"
    end
  end

  def href_for_lightbox(good)
    if good.photos.empty?
      '#'
    else
      "#{good.photos.first.file.url}"
    end
  end

end

app/views/goods/_good.html.slim
.col-md-4
  .thumbinail
      =good_image(good)
      .info.row
        .col-md-6
          p.title
            = link_to good.name, category_good_path(good.category, good)
          p.price
            =number_to_currency good.price
        .col-md-3.actions.pull-right
          button class="btn btn-primary show-button hidden" data-toggle="modal" data-target="#good-#{good.id}"
            span.glyphicon.glyphicon-eye-open
        .col-md-3.actions.pull-right
          = link_to t(:add_to_cart), add_to_cart_category_good_path(good.category, good), method: :post, remote: true, class: 'btn btn-default'
= render 'goods/modal', good: good

app/views/goods/_modal.html.slim
.modal.fade id="good-#{good.id}" tabindex="-1" role="dialog" aria-labelledby="#good-#{good.id}" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-hidden="true"
          | &times;
        h4.modal-title id="#good-#{good.id}"
          = good.name
      .modal-body
        = good_image(good)
        .info
          p.description
            = good.description
          p.price
            = number_to_currency good.price
      .modal-footer
        = link_to t(:add_to_cart), add_to_cart_category_good_path(good.category, good), method: :post, remote: true, class: 'btn btn-success'
        button type="button" class="btn btn-danger" data-dismiss="modal"
          =t(:close)

app/views/goods/_photo.html.slim
.col-md-2.thumbnail
  a.good.cboxElement href="#{img.file.url}"
    = image_tag img.file.small_thumb.url

app/views/goods/add_to_cart.js.erb
$('#current-cart').html('<%= j render @current_cart %>');
$('#current-cart').effect("highlight", "slow");

app/views/goods/index.html.slim
=render @goods

app/views/goods/search_result.html.slim
.results
  -@goods.each do |good|
    .good
      = link_to good.name, good_path(good)
      p.description
        = good.description
      p.price
        = number_to_currency good.price

app/views/goods/show.html.slim
.col-md-12
    ul.breadcrumb
      = render_breadcrumbs :tag => :li, :separator => ""
h3
  =@good.name
.col-md-4
  - if @good.photos.size > 1
    a.good.cboxElement href="#{href_for_lightbox(@good)}"
      = good_image(@good)
  -else
    = good_image(@good)
.col-md-8.images
  .row
    = render partial: 'goods/photo', collection: @good.photos[1..@good.photos.size], as: :img
.col-md-12
  p.description
    =@good.description
  p.price
    = number_to_currency @good.price
  .actions
    = link_to t(:add_to_cart), add_to_cart_category_good_path(@good.category, @good), method: :post, remote: true