config/routes.rb
Rails.application.routes.draw do

  get 'oauths/oauth'

  get 'oauths/callback'

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :categories
    resources :goods
    resources :articles
    resources :orders do
      patch 'change_status', on: :member
    end
  end

  get '/cart', to: 'carts#show', as: 'cart'
  delete '/cart', to: 'carts#destroy', as: 'delete_cart'
  resources :cart_items, only: :destroy do
    patch 'increase', on: :member
    patch 'decrease', on: :member
  end

  resources :orders, only: [:new, :create, :show]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'profile', to: 'users#show', as: :profile
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  get 'article/:id', to: 'articles#show', as: :article

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider

  resources :users, only: [:create, :update]
  resources :sessions, only: [:create]

  get 'search', to: 'search#find', as: :search

  resources :categories, only: [:index, :show], path: 'catalog' do
    resources :goods, only: [:show], path: '' do
      post 'add_to_cart', on: :member
    end
  end

  root 'categories#index'

end

app/models/good.rb
# == Schema Information
#
# Table name: goods
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  description :text
#  price       :decimal(5, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  sale        :boolean          default("false")
#

class Good < ActiveRecord::Base

  extend FriendlyId

  friendly_id :name, use: [:slugged, :finders]

  has_many :cart_items, dependent: :restrict_with_error
  has_many :photos, dependent: :destroy
  belongs_to :category
  validates :name, :price, :category_id, presence: true
  accepts_nested_attributes_for :photos, allow_destroy: true

  scope :sale, -> { where(sale: true) }

  def change_sale
    self.update!(sale: !sale)
  end

  def self.top_selled(limit)
    query = CartItem.select("good_id").group("good_id").order("sum(quantity) DESC").limit(limit).map(&:good_id)
    find(query)
  end

end

app/controllers/admin/goods_controller.rb
class Admin::GoodsController < Admin::AdminController
  load_and_authorize_resource

  def show
    respond_with @good
  end

  def new
    @categories = Category.all
    respond_with @good
  end

  def create
    respond_with(@good = Good.create(good_params), location: admin_path)
  end

  def edit
    @categories = Category.all
    respond_with @good
  end

  def update
    @good.update(good_params)
    respond_with(@good, location: admin_category_path(@good.category))
  end

  private
  def good_params
    params.require(:good).permit(:name, :description, :price, :category_id, :sale, photos_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController

  add_breadcrumb I18n::t(:categories), :categories_path
  respond_to :js
  load_and_authorize_resource
  def index
    respond_with @goods = Good.all
  end

  def show
    add_breadcrumb @good.category.title, category_path(@good.category)
    add_breadcrumb @good.name, category_good_path(@good.category, @good)
    respond_with @good
  end

  def add_to_cart
    @current_cart.add_good(@good)
  end

end

app/helpers/goods_helper.rb
module GoodsHelper

  def good_image(good)
    if good.photos.any? 
      image_tag good.photos.first.file.thumb.url, alt: good.name
    else
      image_tag 'photo-not-available.png'
    end
  end

  def good_image_small(good)
    if good.photos.first
      image_tag good.photos.first.file.small_thumb.url alt: good.name
    else
      "w/o photo"
    end
  end

  def href_for_lightbox(good)
    if good.photos.empty?
      '#'
    else
      "#{good.photos.first.file.url}"
    end
  end

end

app/views/admin/goods/_good.html.slim
.good
  .thumbinail
    h3
      = good.name
    =good_image(good)
  p.description
    =good.description
  p.price
    =number_to_currency good.price
  .actions
    =link_to t(:edit), edit_admin_good_path(good)

app/views/admin/goods/_photos.html.slim
-good.photos.each do |img|
  .img
    = image_tag img.file.small_thumb.url alt: good.name
    = ph.label :_destroy
    = ph.check_box '_destroy'

app/views/admin/goods/edit.html.slim
=nested_form_for(@good, url: admin_good_path(@good), html: { role: 'form', class: 'col-md-6' }) do |f|
  fieldset
    .form-group
      = f.label :name
      = render 'shared/error_message', attribute: :name, model: @good
      = f.text_field :name, class: 'form-control'
    .form-group
      =f.label :category_id
      =f.collection_select :category_id, @categories, :id, :title, {} ,{ class: 'form-control' }
    .form-group
      = f.label :description
      = render 'shared/error_message', attribute: :description, model: @good
      = f.text_area :description, class: 'form-control'
    .form-group
      =f.label :price
      =f.text_field :price, class: 'form-control'
    .form-group
      =f.fields_for :photos, @good.photos do |ph|
        =ph.label :file
        br
        -if ph.object.file.url
          .img
            =image_tag ph.object.file.small_thumb.url 
            = ph.hidden_field :_destroy
            = link_to t(:destroy), '#', class: 'remove_image'
        -else
          =ph.file_field :file
      =f.link_to_add t(:add_photo), :photos
    
    =f.submit t(:save), class: "btn btn-success pull-right"

app/views/admin/goods/new.html.slim
=nested_form_for(@good, url: admin_goods_path, html: { role: 'form', class: 'col-md-6' }) do |f|
  fieldset
    .form-group
      = f.label :name
      = render 'shared/error_message', attribute: :name, model: @good
      = f.text_field :name, class: 'form-control'
    .form-group
      =f.label :category_id
      =f.collection_select :category_id, @categories, :id, :title, {} ,{ class: 'form-control' }
    .form-group
      = f.label :description
      = render 'shared/error_message', attribute: :description, model: @good
      = f.text_area :description, class: 'form-control'
    .form-group
      =f.label :price
      =f.text_field :price, class: 'form-control'
    .form-group
      =f.fields_for :photos, @good.photos.build do |ph|
        =ph.label :file
        =ph.file_field :file
      =f.link_to_add t(:add_photo), :photos
    
    =f.submit t(:save), class: "btn btn-success pull-right"

app/views/admin/goods/show.html.slim
=render @good